# Generated by Django 4.2 on 2023-05-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0002_alter_avatar_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
