# Generated by Django 4.2 on 2023-04-22 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0004_canal_canalmensaje_canalusuario_delete_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canalmensaje',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='canalmensaje',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='canalusuario',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='canalusuario',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Canal',
        ),
        migrations.DeleteModel(
            name='CanalMensaje',
        ),
        migrations.DeleteModel(
            name='CanalUsuario',
        ),
    ]
