# Generated by Django 4.2 on 2023-04-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0006_fav_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='fav',
            name='descripcion',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
