# Generated by Django 4.2 on 2023-04-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(to='accounts.interest', verbose_name='Intereses'),
        ),
    ]
